healthmate/services/urls.py
"""URLs for services."""

from django.conf.urls import url

from .views import ServiceFormView


urlpatterns = [
    url(r'^new/$', ServiceFormView.as_view(), name='create_service'),
]

healthmate/urls.py
"""URLs for website."""
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView

from categories_i18n.views import CategoryListView

from services.models import Service
from services.views import ServicesView, ServiceJSONLayer


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^data.geojson/(?P<id>\d+)$', ServiceJSONLayer.as_view(model=Service,
                                                    properties=('name', 'categories', 'additional_info', 'popupContent',),
                                                    geometry_field="location"), name='data'),
    url(r'^services?/',
        include('healthmate.services.urls', namespace='services')),
    url(r'^category/search/$', CategoryListView.as_view(), name='categories_list'),
    url(r'^category/(?P<id>\d+)/map/$', ServicesView.as_view(), name='category_detail'),
    url(r'^markdown/', include('django_markdown.urls')),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL,  # pragma: no cover
                          document_root=settings.MEDIA_ROOT)  # pragma:no cover

healthmate/services/models.py
"""Contains the Service and ServiceImage models."""

from django.contrib.gis.db import models as geo_models
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.translation import ugettext_lazy as _

from autoslug import AutoSlugField
from django_markdown.models import MarkdownField
from categories_i18n.models import Category


class Service(geo_models.Model):

    """The service model."""

    categories = models.ManyToManyField(Category)
    slug = AutoSlugField(
        populate_from='name', max_length=30, unique=True, editable=False,
        always_update=True)
    name = models.CharField(
        _("Service Name"), max_length=100,
        help_text=_("This name will be used to identify your service."))
    additional_info = MarkdownField(blank=True)
    # Geo Django field to store a point
    location = geo_models.PointField(
        help_text=_("Represented as (longitude, latitude)"),
        default="POINT(0.0 0.0)")

    # You MUST use GeoManager to make Geo Queries
    objects = geo_models.GeoManager()

    def __unicode__(self):
        """Return name representation for service."""
        return self.name

    def get_absolute_url(self):
        """Get profile url for link in admin."""
        return reverse('services:profile', kwargs={
            'slug': self.slug
        })

    @property
    def popupContent(self):
      return '<h2>{}</h2> <p>{}</p>'.format(self.name, self.additional_info)


class ServiceImage(models.Model):

    """Images on the service profile."""

    service = models.ForeignKey(Service, related_name='images')
    image = models.ImageField()
    order = models.PositiveIntegerField(default=1)

    class Meta:
        ordering = ['order']

healthmate/services/forms.py
from django import forms

from leaflet.forms.widgets import LeafletWidget

from models import Service


class ServiceForm(forms.ModelForm):

    class Meta:
        model = Service
        fields = ('name', 'categories', 'location')
        widgets = {'location': LeafletWidget()}

healthmate/services/views.py
"""Views for services."""

from django.views.generic import DetailView, TemplateView, CreateView
from django.utils.translation import ugettext as _

from categories_i18n.models import Category
from djgeojson.views import GeoJSONLayerView

from .models import Service
from .forms import ServiceForm


class ServiceJSONLayer(GeoJSONLayerView):
    def get_queryset(self):
        current_category = Category.objects.get(pk=self.kwargs.get('id', None))
        context = Service.objects.all().filter(categories=current_category)
        return context


class ServiceProfileView(DetailView):

    """A view for service profiles."""

    context_object_name = "service"
    model = Service
    template_name = "services/profile.html"


class ServicesView(TemplateView):

    """A view for services around your location."""
    template_name = "services/map.html"
    settings_overrides = {
        'MIN_ZOOM': 3,
        'MAX_ZOOM': 18,
        'RESET_VIEW': False,
    }

    def get_context_data(self, **kwargs):
        context = super(ServicesView, self).get_context_data(**kwargs)
        category_title = Category.objects.get(pk=self.kwargs.get('id'))
        context['title'] = _(category_title.title)
        return context


class ServiceFormView(CreateView):
    template_name = 'services/create_form.html'
    form_class = ServiceForm
    success_url = '/'

templates/base.html
{% load staticfiles leaflet_tags i18n %}
{% get_current_language as LANGUAGE_CODE %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>healthmate</title>
    <link rel="stylesheet" href="{% static "styles/styles.css" %}" />
    {% leaflet_js %}
    {% leaflet_css %}
    {% leaflet_js plugins="forms" %}
    {% leaflet_css plugins="forms" %}
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
    <script src="{% static "scripts/leaflet-image.js" %}"></script>
  </head>

  <body class="lang-{{ LANGUAGE_CODE }}">
    {% block header %}
        <header role="banner" class="page-header">
            <div class="content-wrapper">
                <a href="/" class="site-logo">Health Mate</a>
                <form class="languagechooser" action="{% url 'set_language' %}" method="post">{% csrf_token %}
                    <input name="next" type="hidden" value="{{ redirect_to }}" />
                    <select name="language">
                        {% get_available_languages as LANGUAGES %}
                        {% get_language_info_list for LANGUAGES as languages %}
                        {% for language in languages %}
                            <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected="selected"{% endif %}>
                                {{ language.name_local }} ({{ language.code }})
                            </option>
                        {% endfor %}
                    </select>
                    <input type="submit" value="Go" />
                </form>
            </div>
        </header>
    {% endblock %}
    <main role="main" class="page-content content-wrapper">
        {% block content %}
        {% endblock %}
    </main>

    {% block footer %}
        <footer role="contentinfo" class="page-footer">
            <div class="content-wrapper">
                <p class="marginless">
                    <small>
                        An open project, started at <a href="http://www.empowerhack.com/">#empowerhack 2015</a>. <a href="https://github.com/empowerhack/HealthMate">Find us on Github</a>
                    </small>
                </p>
            </div>
        </footer>
    {% endblock %}
    {% block postbodyjs %}
    {% endblock postbodyjs %}
  </body>
</html>

templates/categories_i18n/category_list.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
   <div class="contenthead">
        <h2 class="contenthead-title">Find a service</h2>
    </div>
  {% if object_list %}
    <ul class="catlist">
      {% for object in object_list %}
        <li class="catlist-item"><a class="fontawesome-chevron-right" href="{% url 'category_detail' id=object.id %}">{% trans object.title %}</a></li>
      {% endfor %}
    </ul>
  {% endif %}
{% endblock %}

templates/home.html
{% extends "base.html" %}
{% load staticfiles django_markdown i18n %}
{% block content %}
    <div class="contenthead">
        <h1 class="contenthead-title">{% trans "Your Health Mate" %}</h1>
        <p class="contenthead-intro">{% trans "Find and recommend local health support services for you, your family and other refugees." %}</p>
    </div>
    <ul class="gate">
        <li class="gate-route"><a href="{% url 'categories_list' %}" class="btn fontawesome-search">{% trans "Find a service" %}</a></li>
        <li class="gate-route"><a href="{% url 'services:create_service' %}" class="btn fontawesome-plus">{% trans "Add a service" %}</a></li>
    </ul>
{% endblock %}

templates/services/create_form.html
{% extends "base.html" %}
{% load staticfiles django_markdown leaflet_tags i18n %}
{% block content %}
    <div class="contenthead">
        <h2 class="contenthead-title">Add a service</h2>
    </div>
    <form method="POST" action="">
        {% csrf_token %}
        {{ form }}
        <input type="submit"/>
    </form>
{% endblock %}

templates/services/map.html
{% extends "base.html" %}
{% load staticfiles leaflet_tags django_markdown %}
{% block content %}
<div class="contenthead">
    <h1 class="contenthead-title">{{ title }}</h1>
    <a href="{% url 'categories_list' %}" class="back fontawesome-chevron-left">Back to services</a>
</div>

{% leaflet_map "main" callback="main_map_init" settings_overrides=view.settings_overrides %}
    <script type="text/javascript">


        function onEachFeature(feature, layer) {
            if (feature.properties && feature.properties.popupContent) {
                layer.bindPopup(feature.properties.popupContent);
                layer._popup.options.minWidth = 300;
            }
        }

        function main_map_init (map, options) {
            var dataurl = '{% url "data" id=id %}';
            // Download GeoJSON via Ajax
            $.getJSON(dataurl, function (data) {
                // Add GeoJSON layer
                L.geoJson(data, {onEachFeature: onEachFeature}).addTo(map);
            });
            leafletImage(map, function(err, canvas) {
                // now you have canvas
                // example thing to do with that canvas:
                var img = document.createElement('img');
                var dimensions = map.getSize();
                img.width = dimensions.x;
                img.height = dimensions.y;
                img.src = canvas.toDataURL();
                document.getElementById('mapdownload').href = img.src;
            });
        }



    </script>

<div class="center">
    <a class="btn fontawesome-cloud-download" id="mapdownload">Download map</a>
</div>
{% endblock %}